### ISSUE TITLE
Set go version = 1.16

### ISSUE THREAD

**Issue by Ingiboy** [hitian/docker-shadowsocks-with-v2ray-plugin#1]
--FROM golang:alpine as builder
++FROM golang:1.16.15-alpine as builder

With version 1.17+ v2ray compiling, but started with error:
v2ray-plugin panic: qtls.Certificate Request Info doesn't match

**Comment by hitian** [comment]
> golang:1.16.15-alpine

`github.com/v2fly/v2ray-core/v4 v4.38.3` only supports Go 1.16 due to the dependency on quic-go. To compile with other versions of Go, you need to upgrade v2ray-core.

**Comment by Ingiboy** [comment]
Thanks!
